#!/usr/bin/env python3
"""Reconstruct a byte-exact assembly representation of the Intellivision GROM."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "roms" / "GROM, The (1978) (General Instruments) [!].int"
OUTPUT = ROOT / "grom" / "grom.asm"
EXPECTED_BYTES = 2048
CHARACTER_BYTES = 213 * 8


def load_bytes(path: Path) -> bytes:
    data = path.read_bytes()
    if len(data) != EXPECTED_BYTES:
        raise ValueError(f"{path}: expected {EXPECTED_BYTES} bytes, got {len(data)}")
    return data


def render(data: bytes, source_sha256: str) -> str:
    lines = [
        "; Intellivision Graphics ROM (GROM) -- byte-exact reconstruction.",
        "; Generated by grom/reconstruct.py; do not hand-edit this file.",
        f"; Source: {INPUT.relative_to(ROOT)} (SHA-256 {source_sha256})",
        "; GI RO-3-9503: 2048 x 8-bit ROM, addressed by the STIC.",
        "; Offsets $000-$6A7 contain 213 8x8 character patterns; the remaining",
        "; 344 bytes are Executive overflow code/data copied into BACKTAB RAM.",
        "",
        "        ROMW    8",
        "        ORG     $0000",
        "",
        "GROM_CHARACTERS:",
    ]
    offset = 0
    while offset < len(data):
        if offset == CHARACTER_BYTES:
            lines.extend(["", "; Executive overflow (${0:04X})".format(offset), "GROM_EXEC_OVERFLOW:"])
        # Keep the character and EXEC-overflow regions distinct even though
        # their boundary ($06A8) is not aligned to a 16-byte display row.
        count = min(16, CHARACTER_BYTES - offset if offset < CHARACTER_BYTES else len(data) - offset)
        values = ", ".join(f"${value:02X}" for value in data[offset : offset + count])
        lines.append(f"        DECLE   {values}    ; ${offset:04X}")
        offset += count
    lines.extend(["", "        END", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="verify generated source against the GROM dump")
    args = parser.parse_args()

    data = load_bytes(INPUT)
    digest = hashlib.sha256(data).hexdigest()
    expected = render(data, digest)
    if args.verify:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit("grom.asm is absent or does not match the preserved GROM dump")
        print(f"verified {len(data)} 8-bit bytes; SHA-256 {digest}")
    else:
        OUTPUT.write_text(expected)
        print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(data)} 8-bit bytes; SHA-256 {digest}")


if __name__ == "__main__":
    main()
