#!/usr/bin/env python3
"""Reconstruct a byte-exact assembly representation of the ECS EXEC-BASIC ROM."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "roms" / "Entertainment Computer System EXEC-BASIC (1978) (Mattel) [!].int"
OUTPUT = ROOT / "ecs" / "ecs.asm"
PAGE_DECLES = 4096
PAGE_ADDRESSES = (0x2000, 0x7000, 0xE000)
EXPECTED_DECLES = PAGE_DECLES * len(PAGE_ADDRESSES)


def load_decles(path: Path) -> list[int]:
    data = path.read_bytes()
    if len(data) != EXPECTED_DECLES * 2:
        raise ValueError(f"{path}: expected {EXPECTED_DECLES * 2} bytes, got {len(data)}")
    words = [int.from_bytes(data[offset : offset + 2], "big") for offset in range(0, len(data), 2)]
    invalid = [(index, word) for index, word in enumerate(words) if word > 0x3FF]
    if invalid:
        index, word = invalid[0]
        raise ValueError(f"{path}: decle {index:#x} exceeds 10 bits: {word:#06x}")
    return words


def render(words: list[int], source_sha256: str) -> str:
    lines = [
        "; ECS EXEC-BASIC ROM -- byte-exact reconstruction.",
        "; Generated by ecs/reconstruct.py; do not hand-edit this file.",
        f"; Source: {INPUT.relative_to(ROOT)} (SHA-256 {source_sha256})",
        "; Three 4096-decle, 10-bit pages in dump order: $2000, $7000, $E000.",
        "; ECS banking selects the documented page visible in each address window.",
        "",
        "        ROMW    10",
        "",
    ]
    for page_number, address in enumerate(PAGE_ADDRESSES):
        start = page_number * PAGE_DECLES
        end = start + PAGE_DECLES
        lines.extend([f"        ORG     ${address:04X}", "", f"ECS_ROM_PAGE_{page_number}:"])
        for index in range(start, end, 8):
            values = ", ".join(f"${word:03X}" for word in words[index : index + 8])
            lines.append(f"        DECLE   {values}    ; ${address + index - start:04X}")
        lines.append("")
    lines.extend(["        END", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="verify generated source against the ROM dump")
    args = parser.parse_args()
    words = load_decles(INPUT)
    digest = hashlib.sha256(INPUT.read_bytes()).hexdigest()
    expected = render(words, digest)
    if args.verify:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit("ecs.asm is absent or does not match the preserved ROM dump")
        print(f"verified {len(words)} 10-bit decles; SHA-256 {digest}")
    else:
        OUTPUT.write_text(expected)
        print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(words)} 10-bit decles; SHA-256 {digest}")


if __name__ == "__main__":
    main()
