#!/usr/bin/env python3
"""Reconstruct a byte-exact assembly representation of the Intellivoice ROM."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "roms" / "IntelliVoice BIOS (1981) (Mattel).int"
OUTPUT = ROOT / "intellivoice" / "intellivoice.asm"
EXPECTED_BYTES = 2048


def load_bytes(path: Path) -> bytes:
    data = path.read_bytes()
    if len(data) != EXPECTED_BYTES:
        raise ValueError(f"{path}: expected {EXPECTED_BYTES} bytes, got {len(data)}")
    return data


def render(data: bytes, source_sha256: str) -> str:
    lines = [
        "; Intellivoice SP0256-012 ROM -- byte-exact reconstruction.",
        "; Generated by intellivoice/reconstruct.py; do not hand-edit this file.",
        f"; Source: {INPUT.relative_to(ROOT)} (SHA-256 {source_sha256})",
        "; 2048 x 8-bit speech-chip mask ROM; offsets are local to the SP0256.",
        "",
        "        ROMW    8",
        "        ORG     $0000",
        "",
        "SP0256_012_ROM:",
    ]
    for offset in range(0, len(data), 16):
        values = ", ".join(f"${value:02X}" for value in data[offset : offset + 16])
        lines.append(f"        DECLE   {values}    ; ${offset:04X}")
    lines.extend(["", "        END", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="verify generated source against the ROM dump")
    args = parser.parse_args()
    data = load_bytes(INPUT)
    digest = hashlib.sha256(data).hexdigest()
    expected = render(data, digest)
    if args.verify:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit("intellivoice.asm is absent or does not match the preserved ROM dump")
        print(f"verified {len(data)} 8-bit bytes; SHA-256 {digest}")
    else:
        OUTPUT.write_text(expected)
        print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(data)} 8-bit bytes; SHA-256 {digest}")


if __name__ == "__main__":
    main()
