#!/usr/bin/env python3
"""Reconstruct a byte-exact CP1610 assembly representation of the EXEC ROM.

The input is the preserved big-endian, 16-bit-word dump in ``roms/``.  Each
word must use only the low 10 bits: this is the physical width of the EXEC
ROM.  The output deliberately uses DECLE data rather than guessing at code
versus tables, so assembling it preserves every original word exactly.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "roms" / "Executive ROM, The (1978) (Mattel).int"
OUTPUT = ROOT / "executive" / "executive.asm"
EXPECTED_DECLES = 4096

# Entry points documented in executive/ROM.md.  Labels are annotations only:
# DECLE output remains an exact representation of the preserved ROM dump.
ENTRY_POINTS = {
    0x1000: "EXEC_RESET_ENTRY",
    0x1004: "EXEC_STIC_VBLANK_ENTRY",
    0x1126: "EXEC_VBLANK",
    0x1668: "EXEC_SIGN_EXTEND_R0",
    0x169E: "EXEC_RANDOM",
    0x1738: "EXEC_ZERO_MEMORY",
    0x1741: "EXEC_FILL_MEMORY",
    0x1777: "EXEC_GET_CARD_POSITION",
    0x17C1: "EXEC_PUSH_R1_R4",
    0x1867: "EXEC_WRITE_STRING_AT",
    0x187B: "EXEC_WRITE_INLINE_STRING",
    0x18AD: "EXEC_WRITE_NUMBER_ZERO_PADDED",
    0x18C5: "EXEC_WRITE_NUMBER_SPACE_PADDED",
    0x1910: "EXEC_READ_NUMBER",
    0x1A83: "EXEC_SILENCE_SOUND",
    0x1B27: "EXEC_PLAY_FLUTE",
    0x1B5D: "EXEC_PLAY_ORGAN",
    0x1B95: "EXEC_STOCK_SOUND",
    0x1BBE: "EXEC_NOISE_ENVELOPE",
    0x1DD8: "EXEC_SQUARE",
    0x1DDC: "EXEC_MULTIPLY",
    0x1DF8: "EXEC_DIVIDE",
    0x1EC4: "EXEC_RAZZ",
    0x1ED5: "EXEC_CHEER",
    0x1F1D: "EXEC_WHISTLE",
}


def load_decles(path: Path) -> list[int]:
    data = path.read_bytes()
    if len(data) != EXPECTED_DECLES * 2:
        raise ValueError(f"{path}: expected {EXPECTED_DECLES * 2} bytes, got {len(data)}")
    words = [int.from_bytes(data[offset : offset + 2], "big") for offset in range(0, len(data), 2)]
    invalid = [(index, word) for index, word in enumerate(words) if word > 0x3FF]
    if invalid:
        index, word = invalid[0]
        raise ValueError(f"{path}: decle {index:#x} exceeds 10 bits: {word:#06x}")
    return words


def render(words: list[int], source_sha256: str) -> str:
    lines = [
        "; Intellivision Executive ROM -- byte-exact reconstruction.",
        "; Generated by executive/reconstruct.py; do not hand-edit this file.",
        f"; Source: {INPUT.relative_to(ROOT)} (SHA-256 {source_sha256})",
        "; The ROM is 4096 10-bit decles mapped at $1000-$1FFF.",
        "",
        "        ROMW    10",
        "        ORG     $1000",
        "",
    ]
    index = 0
    while index < len(words):
        address = 0x1000 + index
        label = ENTRY_POINTS.get(address)
        if label:
            lines.extend([f"; {label} (${address:04X})", f"{label}:"])
        # Do not let a DECLE group cross a documented entry point: the label
        # must resolve to its exact word address, including unaligned entries.
        next_entry = min(
            (entry - 0x1000 for entry in ENTRY_POINTS if entry > address),
            default=len(words),
        )
        count = min(8, next_entry - index)
        values = ", ".join(f"${word:03X}" for word in words[index : index + count])
        lines.append(f"        DECLE   {values}    ; ${address:04X}")
        index += count
    lines.extend(["", "        END", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="verify generated source against the ROM dump")
    args = parser.parse_args()

    words = load_decles(INPUT)
    digest = hashlib.sha256(INPUT.read_bytes()).hexdigest()
    expected = render(words, digest)
    if args.verify:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit("executive.asm is absent or does not match the preserved ROM dump")
        print(f"verified {len(words)} 10-bit decles; SHA-256 {digest}")
    else:
        OUTPUT.write_text(expected)
        print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(words)} 10-bit decles; SHA-256 {digest}")


if __name__ == "__main__":
    main()
